### ISSUE TITLE
zeromq fix

### ISSUE THREAD

**Issue by vik-y** [tigerlinux/openstack-ocata-installer-centos7#3]
Even after all those patches made to fix the zeromq package problem the installation still fails for me  in CentOS 7 due to zeromq. 

I managed to fix it by doing the following : 
```sh
yum erase -f zeromq
yum versionlock clear
yum install python-zmq
```
For the keyring issue below fixes the problem. 
```sh
yum remove python-keyring
yum install python-keyring 
```

I think replacing zeromq with python-zmq can fix the zeromq problem (I'm not sure but). And regarding the python-keyring failure I'm not sure why it happens but the above solution fixes it.

**Comment by tigerlinux** [comment]
Weird. I could not reproduce the problem (using a clean centos7 machine) with any of my last two installers (ocata and pike). I think is something very specific to your centos installation.
